// Sample Maui/Molokai listings for the demo. Edit these freely.
// In production, replace with a live MLS/IDX feed (see README).
export default [
  {
    mlsId: "401231",
    type: "condo",
    area: "Kihei",
    island: "Maui",
    price: 785000,
    beds: 2,
    baths: 2,
    sqft: 920,
    tenure: "fee simple",
    hoaFee: 780,
    strEligible: true,
    strNote: "Permitted vacation rental (Minatoya-list building)",
    status: "Active",
    description:
      "Top-floor unit with ocean views, walk to Kamaole Beach, strong vacation-rental history.",
  },
  {
    mlsId: "401588",
    type: "condo",
    area: "Kihei",
    island: "Maui",
    price: 549000,
    beds: 1,
    baths: 1,
    sqft: 640,
    tenure: "leasehold",
    hoaFee: 540,
    strEligible: false,
    status: "Active",
    description:
      "Affordable entry near the beach; note this one is leasehold, not fee simple, and is residential-use only.",
  },
  {
    mlsId: "402004",
    type: "townhouse",
    area: "Kihei",
    island: "Maui",
    price: 925000,
    beds: 3,
    baths: 2.5,
    sqft: 1480,
    tenure: "fee simple",
    hoaFee: 410,
    strEligible: false,
    status: "Active",
    description: "Townhome with garage; long-term residential use, popular with families.",
  },
  {
    mlsId: "403117",
    type: "single-family",
    area: "Wailea",
    island: "Maui",
    price: 3950000,
    beds: 4,
    baths: 4.5,
    sqft: 3650,
    tenure: "fee simple",
    strEligible: false,
    status: "Active",
    description: "Luxury home on the golf course with pool and sweeping resort views.",
  },
  {
    mlsId: "403260",
    type: "condo",
    area: "Wailea",
    island: "Maui",
    price: 2150000,
    beds: 3,
    baths: 3,
    sqft: 1820,
    tenure: "fee simple",
    hoaFee: 2100,
    strEligible: true,
    strNote: "Resort-zoned, legal vacation rental",
    status: "Active",
    description: "Resort condo with concierge, pools, and steps to Wailea Beach.",
  },
  {
    mlsId: "404021",
    type: "condo",
    area: "Kaanapali",
    island: "Maui",
    price: 1250000,
    beds: 2,
    baths: 2,
    sqft: 1100,
    tenure: "fee simple",
    hoaFee: 1450,
    strEligible: true,
    strNote: "Resort-zoned, legal vacation rental",
    status: "Active",
    description:
      "Oceanfront unit in the Kaanapali resort area with sunset views and on-site amenities.",
  },
  {
    mlsId: "405310",
    type: "single-family",
    area: "Paia",
    island: "Maui",
    price: 1690000,
    beds: 3,
    baths: 2,
    sqft: 1560,
    tenure: "fee simple",
    strEligible: false,
    status: "Active",
    description: "Plantation-style home walkable to Paia town and Baldwin Beach.",
  },
  {
    mlsId: "406145",
    type: "single-family",
    area: "Upcountry",
    island: "Maui",
    price: 1395000,
    beds: 3,
    baths: 2,
    sqft: 1740,
    tenure: "fee simple",
    zoning: "Ag-adjacent residential",
    strEligible: false,
    status: "Active",
    description:
      "Makawao home on half an acre; possible ohana potential, subject to Upcountry water-meter availability.",
  },
  {
    mlsId: "407002",
    type: "single-family",
    area: "Kahului",
    island: "Maui",
    price: 899000,
    beds: 4,
    baths: 2,
    sqft: 1600,
    tenure: "fee simple",
    strEligible: false,
    status: "Active",
    description: "Central, well-priced family home close to schools, shops, and the airport.",
  },
  {
    mlsId: "408500",
    type: "land",
    area: "Hana",
    island: "Maui",
    price: 675000,
    acres: 2.1,
    tenure: "fee simple",
    zoning: "Agricultural",
    strEligible: false,
    status: "Active",
    description:
      "Lush 2-acre ag parcel with off-grid potential; buyer to confirm water and dwelling rights.",
  },
  {
    mlsId: "MOL1102",
    type: "single-family",
    area: "Kaunakakai",
    island: "Molokai",
    price: 625000,
    beds: 3,
    baths: 2,
    sqft: 1450,
    tenure: "fee simple",
    strEligible: false,
    status: "Active",
    description:
      "Quiet second-home near town, ideal for buyers wanting an authentic Molokai lifestyle.",
  },
  {
    mlsId: "MOL1140",
    type: "condo",
    area: "West Molokai",
    island: "Molokai",
    price: 385000,
    beds: 1,
    baths: 1,
    sqft: 720,
    tenure: "fee simple",
    hoaFee: 480,
    strEligible: true,
    strNote: "Zoned for vacation rental",
    status: "Active",
    description: "Oceanfront condo with vacation-rental potential and big sunset views.",
  },
];
